### ISSUE TITLE
Bug - Incorrect scaling of LinearJointDrive when inside a container

### ISSUE THREAD

**Issue by danieljharris** [ExtendRealityLtd/Tilia.Interactions.Controllables.Unity#186] opened 2022-05-18 21:22 UTC
### Environment

* Code source: Controllables package v2.2.2
* Platform version: Unity 2021.3.2f1
* All packages used:
    "io.extendreality.tilia.camerarigs.trackedalias.unity": "2.0.2"
    "io.extendreality.tilia.camerarigs.xrpluginframework.unity": "2.0.2"
    "io.extendreality.tilia.input.unityinputsystem": "2.0.2"
    "io.extendreality.tilia.interactions.controllables.unity": "2.2.2"
    "io.extendreality.tilia.interactions.interactables.unity": "2.4.0"

### Steps to reproduce

1. Create new project
2. Setup a standard Tilia camera rig with UnityInputSystem mapping (the camera rig and input methods should not matter, as long as you can grab the LinearJointDrive it should be reproducable)
<img width="246" alt="image" src="https://user-images.githubusercontent.com/1362512/169147129-756037ed-dd4d-4b20-a2d9-7dfdbc7f4807.png">
3. Create an empty "Container" object and set the x scale to 0.1
<img width="366" alt="image" src="https://user-images.githubusercontent.com/1362512/169146982-31a778cd-5af0-4029-9660-4de284254347.png">
4. Create a "Interactions.LinearJointDrive" inside the "Container"
<img width="242" alt="image" src="https://user-images.githubusercontent.com/1362512/169147484-e440df53-4f50-490a-b62e-ac67eead5823.png">
5. Play the scene, grab the LinearJointDrive and move to the left

6. In the Unity editor observe the that LinearJointDrive has moved outside the "Container" object and past the Gizmo

<img width="405" alt="image" src="https://user-images.githubusercontent.com/1362512/169148016-690c7391-19a8-421d-a995-3640b74116ee.png">

### Expected behavior

The LinearJointDrive should be limited to move to within the "Container" object and should be inside the Gizmo

### Current behavior

The LinearJointDrive is free to move outside the "Container" object and outside the Gizmo. I believe this may be caused by LinearJointDrive's DriveLimit using world scaling while other logic uses local scaling. However, I have unfortunately been unable to identify any further causes of this issue.

My first thought was to change the LinearJointDrive's "Drive Limit" to match the "Container"'s x scale (in this case 0.1). However, this caused further issues around limiting the values that are outputted by LinearJointDrive's "Value Changed" events.

**Comment by thestonefox** [comment] 2022-05-19 07:22
I'm not sure where the issue is, its either in the gizmo drawing and its not updating the gizmo to the correct length

or its in the drive limit being determined in world space (this may actually be because perhaps a joint limit is determined this way so the transform drive is copying it).

A workaround would be to:

with container set to x0.1
![image](https://user-images.githubusercontent.com/1029673/169235200-16e18be1-676e-4977-8f57-748d4e457296.png)

the LinearJointDrive would have its x scale set to 10
![image](https://user-images.githubusercontent.com/1029673/169235242-df90922f-6bc3-4102-8049-f95f9c50a7b2.png)

and then the internal interactable would then need downscaling to match the container scale at x0.1
![image](https://user-images.githubusercontent.com/1029673/169235302-770f147e-663b-4993-a812-2704c8dfd3d8.png)

This now at least draws the gizmo at the expected length to the world drive limit.

I'll need to mull over what the actual correct behaviour should be and also based on how the joint drives work based on the restrictions imposed by the unity joint system.

**Comment by danieljharris** [comment] 2022-05-19 20:42
Although that workaround fixes the gizmo it still doesn't allow the scaling to work intuitively. To me the correct behaviour would be to have the min and max bounds scale accordingly with the scale of the container.

I think I may have found a solution. In LinearDrive's CalculateDriveLimits if you alter the code to use world scale via "transform.lossyScale" instead of "newLimit" it correctly scales the min and max bounds with the container.

If you agree this would be the correct behaviour I'm more than happy to make a PR with an improved version of this fix if you would like @thestonefox?

### Below is the quick fix solution:
From:
```cs
public virtual FloatRange CalculateDriveLimits(float newLimit)
{
    if (!isActiveAndEnabled)
    {
        return FloatRange.MinMax;
    }

    float motionLimit = Mathf.Abs(newLimit * 0.5f);
    return new FloatRange(-motionLimit, motionLimit);
}
```

To:
```cs
public virtual FloatRange CalculateDriveLimits(float newLimit)
{
    if (!isActiveAndEnabled)
    {
        return FloatRange.MinMax;
    }
    newLimit = transform.lossyScale.x; // Scales from world size

    float motionLimit = Mathf.Abs(newLimit * 0.5f);
    return new FloatRange(-motionLimit, motionLimit);
}
```

**Comment by thestonefox** [comment] 2022-05-20 04:41
But does this have the same effect on the linear joint drive as well?

Because that's my concern is that the joint drive limits are calculated in world space because of unity joints. I'm not sure but it needs checking. Otherwise the two linear drives will be inconsistent with each other

**Comment by thestonefox** [comment] 2022-05-24 12:59
a quick interim could be to at least get the gizmo to render correctly, even though the actual outcome is not intended.

so if you size the outer container, then the inner control is still world space but the gizmo clearly shows that.

i think at the very least that is a fix for the current implementation

**Comment by danieljharris** [comment] 2022-05-24 13:06
Yes, that should be an easier fix to at least make the existing implementation more obvious with how it works and make the gizmo consistent with linear drive functionality.

However, I would still love to see a full fix that makes the linear joint scale proportionately with its container. But I understand that is a more complex problem to solve.

**Comment by thestonefox** [comment] 2022-07-15 06:43
Fixed somewhat with https://github.com/ExtendRealityLtd/Tilia.Interactions.Controllables.Unity/pull/192

**Closed by thestonefox** 2022-07-15 06:43 UTC
Labels: bug
